### ISSUE TITLE
The ligigl implementation crashes with non-disk topology meshes

### ISSUE THREAD

**Issue by FrankEscobar** [jiangzhongshi/Scaffold-Map#4]
The weird fact is that I think that old versions worked even on that ones.

Regards, F.

**Comment by jiangzhongshi** [comment]
Hi Frank,

Thanks for letting me know. During my process of simplification of the code, in order to integrate into libigl codebase, I dropped some of the functionality. 
I will find time to clarify there.

Thanks for letting me know!

Best,
Zhongshi
